# -*- coding: utf-8 -*-
"""orcamento_mudanca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJDTAMWjnCxOWv2gLuqbuuUkHoX5BMAd
"""

nome = input("Informar seu nome: ")
endereco = input("Infomar seu endereço: ")
enrega = input("Ifomar enderço de entrega: ")
km_media = float(input("Qual a quilometragem média?"))
caixa_maior = 60*50*50
caixa_menor = 35*25*25
qtd_caixaG = (caixa_maior*(int(input("Quantas caixas maiores? "))))/100000
qtd_caixaM = (caixa_menor*(int(input("Quantas caixas menores? "))))/1000000
pergunta1 = input("Vai levar a geladeira? ")
if pergunta1 == ("sim"):
  geladeira = float(input("Insira as medidas da geladeira em metros cubicos: "))
else:
   geladeira = 0
pergunta2 = input(("Vai levar a máquina de lavar? "))
if pergunta2 == ("sim"):
  maquina = float(input("Insira as medidas da  máquina de lavar em metros cubicos: "))
else:
  maquina = 0

pergunta3 = input("Vai levar os demais móveis? ")
if pergunta3 == ("sim"):

 outros = float(input("insira as medidas do somatório dos demais móveis em metros cubicos:"))
else:
  outros = 0

Mcubi_max = geladeira + maquina + outros + qtd_caixaG + qtd_caixaM
orca_i = Mcubi_max * 5
orcamento = orca_i*km_media
print("Nome:",nome)
print("endereço de entrega/destino:",endereco,"para",enrega)
print("Orçamento:",orcamento, "R$")